version: '3.8'

services:
  podsync:
    # container_name: podsync
    # image: odayny/podsync:latest
    build:
      context: .
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - podsync-data:/go/src/app/data/
      - ./config.toml:/go/src/app/config.toml:ro
volumes:
  podsync-data:
